"""create study plan subjects table

Revision ID: 03a79339bb0a
Revises: 6d7c91c105dd
Create Date: 2026-08-07 10:24:13.671890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03a79339bb0a'
down_revision: Union[str, Sequence[str], None] = '6d7c91c105dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_plan_subjects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_id'], ['study_plans.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_plan_subjects_study_plan_id'), 'study_plan_subjects', ['study_plan_id'], unique=False)
    op.create_index(op.f('ix_study_plan_subjects_subject_id'), 'study_plan_subjects', ['subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_plan_subjects_subject_id'), table_name='study_plan_subjects')
    op.drop_index(op.f('ix_study_plan_subjects_study_plan_id'), table_name='study_plan_subjects')
    op.drop_table('study_plan_subjects')
    # ### end Alembic commands ###
