"""create student profiles table

Revision ID: b046aeca3572
Revises: 475412465ba6
Create Date: 2026-08-05 10:36:53.515428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b046aeca3572'
down_revision: Union[str, Sequence[str], None] = '475412465ba6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('study_goal', sa.String(length=255), nullable=False),
    sa.Column('exam_name', sa.String(length=255), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('weekly_hours', sa.Integer(), nullable=False),
    sa.Column('study_days', sa.String(length=255), nullable=False),
    sa.Column('education_level', sa.String(length=100), nullable=False),
    sa.Column('experience_level', sa.String(length=100), nullable=False),
    sa.Column('preferred_shift', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profiles')
    # ### end Alembic commands ###
