"""create study sessions table

Revision ID: e0131e7c9ceb
Revises: 03a79339bb0a
Create Date: 2026-08-07 10:31:45.663955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0131e7c9ceb'
down_revision: Union[str, Sequence[str], None] = '03a79339bb0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_plan_subject_id', sa.Integer(), nullable=False),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_plan_subject_id'], ['study_plan_subjects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_sessions_session_date'), 'study_sessions', ['session_date'], unique=False)
    op.create_index(op.f('ix_study_sessions_study_plan_subject_id'), 'study_sessions', ['study_plan_subject_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_study_sessions_study_plan_subject_id'), table_name='study_sessions')
    op.drop_index(op.f('ix_study_sessions_session_date'), table_name='study_sessions')
    op.drop_table('study_sessions')
    # ### end Alembic commands ###
